/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/parachoques.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="ProtectorSuperior" geometry={nodes.ProtectorSuperior.geometry} material={materials.PlasticoGris} position={[2, 0.89, 0]} />
        <mesh name="ParachoqueInferior" geometry={nodes.ParachoqueInferior.geometry} material={materials.PlasticoGris} position={[2.02, 0.37, 0]} />
        <mesh name="Parrilla" geometry={nodes.Parrilla.geometry} material={materials.PlasticoGris} position={[2.09, 0.75, 0]} />
        <mesh name="ProtectorInferior" geometry={nodes.ProtectorInferior.geometry} material={materials.PlasticoGris} position={[1.71, 0.35, 0]} />
        <mesh name="GuardapolvoCocuyos" geometry={nodes.GuardapolvoCocuyos.geometry} material={materials.PlasticoGris} position={[2.03, 0.59, -0.74]} />
        <mesh name="Placa" geometry={nodes.Placa.geometry} material={materials.PlasticoGris} position={[2.26, 0.57, 0.01]} />
        <group name="Cocuyos_Derecho" position={[2.01, 0.58, -0.74]}>
          <mesh name="105" geometry={nodes['105'].geometry} material={materials.PlasticoGris} />
          <mesh name="105_1" geometry={nodes['105_1'].geometry} material={materials.PlasticoTransparente} />
        </group>
        <mesh name="BordeParrilla" geometry={nodes.BordeParrilla.geometry} material={materials.PlasticoGris} position={[2.14, 0.77, 0.03]} />
        <mesh name="ParachoqueSuperior" geometry={nodes.ParachoqueSuperior.geometry} material={materials.MetalGris} position={[1.93, 0.67, 0.11]} />
        <group name="LucesDelantera" position={[1.9, 0.82, 0]}>
          <mesh name="134" geometry={nodes['134'].geometry} material={materials.PlasticoTransparente} />
          <mesh name="134_1" geometry={nodes['134_1'].geometry} material={materials.Chrome} />
          <mesh name="134_2" geometry={nodes['134_2'].geometry} material={materials.PlasticoGris} />
        </group>
        <group name="BombillaPrincipales" position={[1.55, 0.83, 0]}>
          <mesh name="105001" geometry={nodes['105001'].geometry} material={materials.PlasticoTransparente} />
          <mesh name="105001_1" geometry={nodes['105001_1'].geometry} material={materials.PlasticoGris} />
        </group>
        <mesh name="BarraHorizontal" geometry={nodes.BarraHorizontal.geometry} material={materials.Metal} position={[1, 0.86, -0.12]} />
        <mesh name="Pieza1" geometry={nodes.Pieza1.geometry} material={materials.Metal} position={[1.93, 0.79, 0.06]} />
        <mesh name="Pieza2" geometry={nodes.Pieza2.geometry} material={materials.Metal} position={[1.85, 0.8, 0.07]} />
        <mesh name="Pieza3" geometry={nodes.Pieza3.geometry} material={materials.PlasticoGris} position={[1.72, 0.72, 0.02]} />
        <mesh name="JeepCapo" geometry={nodes.JeepCapo.geometry} material={materials.Chrome} />
        <mesh name="Parabrisa_Delantero" geometry={nodes.Parabrisa_Delantero.geometry} material={materials.Vidrio} />
        <mesh name="GuardapolvoCocuyos001" geometry={nodes.GuardapolvoCocuyos001.geometry} material={materials.PlasticoGris} position={[2.03, 0.59, 0.73]} />
        <group name="Cocuyos_Izquierdo" position={[2.01, 0.58, 0.74]}>
          <mesh name="105002" geometry={nodes['105002'].geometry} material={materials.PlasticoGris} />
          <mesh name="105002_1" geometry={nodes['105002_1'].geometry} material={materials.PlasticoTransparente} />
        </group>
        <mesh name="Capo" geometry={nodes.Capo.geometry} material={materials.MetalGris} />
      </group>
    </group>
  )
}

useGLTF.preload('/parachoques.gltf')
