/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/puertaTrasera.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="vidrio_PT" position={[-0.67, 1.3, -0.7]}>
          <mesh name="2001" geometry={nodes['2001'].geometry} material={materials.Vidrio} />
          <mesh name="2001_1" geometry={nodes['2001_1'].geometry} material={materials.PlasticoGris} />
        </group>
        <mesh name="MallaCorneta_PT" geometry={nodes.MallaCorneta_PT.geometry} material={materials.PlasticoGris} position={[-0.48, 0.57, -0.63]} />
        <mesh name="5" geometry={nodes['5'].geometry} material={materials.PlasticoGris} position={[-0.56, 0.9, -0.69]} />
        <mesh name="TapaInterna_PT" geometry={nodes.TapaInterna_PT.geometry} material={materials.Interior} position={[-0.69, 0.76, -0.69]} />
        <mesh name="PuertaTracera" geometry={nodes.PuertaTracera.geometry} material={materials.MetalGris} position={[-0.7, 0.97, -0.76]} />
        <mesh name="Cerradura_PT" geometry={nodes.Cerradura_PT.geometry} material={materials.Metal} position={[-1.07, 0.88, -0.78]} />
        <mesh name="Bisagras" geometry={nodes.Bisagras.geometry} material={materials.Metal} position={[-0.23, 0.91, -0.76]} />
        <mesh name="cerradua1_PT" geometry={nodes.cerradua1_PT.geometry} material={materials.Metal} position={[-0.26, 0.61, -0.76]} />
        <mesh name="Corneta_PT" geometry={nodes.Corneta_PT.geometry} material={materials.PlasticoGris} position={[-0.48, 0.57, -0.7]} />
        <mesh name="MecanismoInterno" geometry={nodes.MecanismoInterno.geometry} material={materials.Metal} position={[-0.64, 0.79, -0.76]} />
        <mesh name="Manila_PT" geometry={nodes.Manila_PT.geometry} material={materials.PlasticoGris} position={[-1.08, 1.25, -0.75]} />
        <mesh name="TapaNegraManilla" geometry={nodes.TapaNegraManilla.geometry} material={materials.PlasticoGris} position={[-1.04, 1.32, -0.71]} />
        <mesh name="TapaNegraSuperior_PT" geometry={nodes.TapaNegraSuperior_PT.geometry} material={materials.PlasticoGris} position={[-0.33, 1.31, -0.72]} />
        <mesh name="20001" geometry={nodes['20001'].geometry} material={materials.PlasticoGris} position={[-0.76, 0.83, -0.68]} />
        <mesh name="tapanegraInferior_PT" geometry={nodes.tapanegraInferior_PT.geometry} material={materials.PlasticoGris} position={[-0.58, 0.41, -0.81]} />
        <mesh name="26" geometry={nodes['26'].geometry} material={materials.Metal} position={[-0.52, 1.03, -0.73]} />
        <mesh name="GomaPuertaTracera" geometry={nodes.GomaPuertaTracera.geometry} material={materials.Juntas} position={[-0.68, 0.97, -0.72]} />
      </group>
    </group>
  )
}

useGLTF.preload('/puertaTrasera.gltf')
