/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/puertaDelantera.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="gomaPuerta" geometry={nodes.gomaPuerta.geometry} material={materials.Juntas} position={[0.19, 0.91, -0.74]} />
        <mesh name="Puerta" geometry={nodes.Puerta.geometry} material={materials.MetalGris} position={[0.27, 0.77, -0.8]} />
        <group name="vidrio" position={[0.13, 1.26, -0.74]}>
          <mesh name="4" geometry={nodes['4'].geometry} material={materials.Vidrio} />
          <mesh name="4_1" geometry={nodes['4_1'].geometry} material={materials.PlasticoGris} />
        </group>
        <mesh name="GomaVidrio" geometry={nodes.GomaVidrio.geometry} material={materials.PlasticoGris} position={[0.12, 1.33, -0.7]} />
        <mesh name="TapaInternaRetrovisor" geometry={nodes.TapaInternaRetrovisor.geometry} material={materials.PlasticoGris} position={[0.65, 1.13, -0.75]} />
        <mesh name="7" geometry={nodes['7'].geometry} material={materials.Interior} position={[0.25, 0.76, -0.72]} />
        <mesh name="corneta" geometry={nodes.corneta.geometry} material={materials.PlasticoGris} position={[0.52, 0.54, -0.74]} />
        <mesh name="9" geometry={nodes['9'].geometry} material={materials.PlasticoGris} position={[0.52, 0.53, -0.7]} />
        <mesh name="10" geometry={nodes['10'].geometry} material={materials.Metal} position={[-0.23, 0.76, -0.77]} />
        <mesh name="Bisagra1" geometry={nodes.Bisagra1.geometry} material={materials.Metal} position={[0.76, 0.54, -0.81]} />
        <mesh name="13" geometry={nodes['13'].geometry} material={materials.Metal} position={[-0.17, 0.73, -0.78]} />
        <mesh name="ManillaInterna" geometry={nodes.ManillaInterna.geometry} material={materials.PlasticoGris} position={[0.51, 0.71, -0.64]} />
        <mesh name="17" geometry={nodes['17'].geometry} material={materials.Metal} position={[0.45, 0.72, -0.71]} />
        <mesh name="TapaNegraSuperior" geometry={nodes.TapaNegraSuperior.geometry} material={materials.PlasticoGris} position={[-0.26, 1.3, -0.73]} />
        <mesh name="20" geometry={nodes['20'].geometry} material={materials.PlasticoGris} position={[0.37, 0.8, -0.69]} />
        <mesh name="TapaNegraInferior" geometry={nodes.TapaNegraInferior.geometry} material={materials.PlasticoGris} position={[0.25, 0.39, -0.82]} />
        <mesh name="Llave" geometry={nodes.Llave.geometry} material={materials.PlasticoGris} position={[-0.14, 0.99, -0.94]} />
        <mesh name="31001" geometry={nodes['31001'].geometry} material={materials.Interior} position={[0.48, 0.94, -0.72]} />
        <mesh name="Manilla" geometry={nodes.Manilla.geometry} material={materials.MetalGris} position={[-0.06, 0.99, -0.88]} />
        <mesh name="compass" geometry={nodes.compass.geometry} material={materials.Chrome} position={[0.5, 0.63, -0.86]} />
        <mesh name="cerradura" geometry={nodes.cerradura.geometry} material={materials.PlasticoGris} position={[-0.14, 0.99, -0.89]} />
        <group name="retrovisor" position={[0.63, 1.15, -0.91]}>
          <mesh name="61" geometry={nodes['61'].geometry} material={materials.Chrome} />
          <mesh name="61_1" geometry={nodes['61_1'].geometry} material={materials.PlasticoGris} />
        </group>
        <mesh name="70001" geometry={nodes['70001'].geometry} material={materials.PlasticoGris} position={[0.19, 0.81, -0.69]} />
        <mesh name="71001" geometry={nodes['71001'].geometry} material={materials.Interior} position={[0.23, 0.73, -0.68]} />
        <mesh name="Bisagra2" geometry={nodes.Bisagra2.geometry} material={materials.Metal} position={[0.76, 0.8, -0.81]} />
      </group>
    </group>
  )
}

useGLTF.preload('/puertaDelantera.gltf')
